In [1]:
 import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Dimension of array


In [6]:
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)  # to check dimension of array

20
<class 'numpy.ndarray'>
0


In [7]:
# 1d array


In [8]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)  # to check dimension of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [9]:
# 2d arr


In [10]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(type(arr))
print(arr.ndim)  # to check dimension of array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [11]:
# 3d array


In [14]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)
print(type(arr))
print(arr.ndim)  # to check dimension of array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [15]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:


In [34]:
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [35]:
# NumPy array indexing


In [36]:
import numpy as np
arr = np.array([1,2,3,4])

print(arr[0])

1


In [37]:
m = ([41, 23, 54, 75, 76, 23, 65, 27, 65, 26, 73, 84, 17, 74, 85, 33, 77])
print("The Second element is ", m[2])
print("The sixth element is ", m[6])
print("The eighth element is ", m[8])
print("The sum of element is ", m[2] + m[6] + m[8])


The Second element is  54
The sixth element is  65
The eighth element is  65
The sum of element is  184


In [38]:
# Access 2-D Array


In [39]:
arr = np.array([[10, 20, 30, 40,50], [60,70,80,90,100]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  20


In [40]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print('4th element on 1st row: ', arr[0, 3])

4th element on 1st row:  40


In [41]:
arr = np.array([[10, 20, 30, 40,50], [60,70,80,90,100]])
print('1st element on 2nd row: ', arr[1, 0])

1st element on 2nd row:  60


In [43]:
arr = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print("last element on 2nd row: ", arr[1, 4])

last element on 2nd row:  100


In [45]:
arr = np.array([[10, 20, 30, 40, 50], 
                [60, 70, 80, 90, 100]])
print("First element of 1st row:", arr[0,0])
print("Last element of 2nd row:", arr[1,4])
print("Sum of both the element is:", arr[0,0] + arr[1,4])

First element of 1st row: 10
Last element of 2nd row: 100
Sum of both the element is: 110


In [46]:
# Access 3-D Array


In [47]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,2])

12


In [49]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2]+arr[1,1,2])

18


In [50]:
# Slicing arrays


In [55]:
# 2-D Array
arr = np.array([[10, 20, 30, 40,50], 
                [60,70,80,90,100]])
print(arr[1,0:2])

# 3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0:2])

arr = np.array([[[1, 2, 3], [4, 5, 6]], 
                [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,0:])

[60 70]
[10 11]
[10 11 12]


In [56]:
# Checking the data type of an array


In [57]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [58]:
arr = np.array(['animals', 'bat', 'cat'])
print(arr.dtype)

<U7


In [59]:
# Creating arrays with a defined data type


In [62]:
ar = np.array([1,2,3,4], dtype = 'S')
print(ar)
print(ar.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [63]:
# Create an array with data types 4 bytes integer


In [64]:
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [66]:
# Numpy array shape
# The shape of an array is the number of elements in each dimensions


In [39]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr.shape)

(2, 4)


In [42]:
arr = np.array([[[1,2,3,4],
                 [5,6,7,8], 
                 [10,11,12,13]]])
print(arr.shape)

(1, 3, 4)


In [43]:
# Joining numpy arrays


In [44]:
arr1 = np.array([1,2,3])
arr2= np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [45]:
# Joining 2-D arrays


In [46]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [47]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis = 0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Splitting numpy arrays


In [50]:
# splitting the array in three parts

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [51]:
# splitting the array in four parts

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [54]:
# Ravel and flatten
# it converts multi-dimensional array into 1-D array


In [55]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimensions is", m.ndim)
n = m.ravel()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensions is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [56]:
m = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(m)
print("dimensions is", m.ndim)
n = m.flatten()
print(n)
print("now the new dimension is", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimensions is 3
[1 2 3 4 5 6 7 8 9]
now the new dimension is 1


In [57]:
c = np.array([[[[1,2,3], [4,5,6], [7,8,9]]]])
print(c)
print("the dimension is", c.ndim)
d = c.ravel()
print(d)
print("the dimension is", d.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
the dimension is 4
[1 2 3 4 5 6 7 8 9]
the dimension is 1


In [58]:
# Unique function


In [60]:
k = np.array([1,22,45,3,65,3,4,7,7,5,4,1,45,77,95,23])
print(k)
x = np.unique(k)
print(x)

[ 1 22 45  3 65  3  4  7  7  5  4  1 45 77 95 23]
[ 1  3  4  5  7 22 23 45 65 77 95]


In [61]:
k = np.array([1,22,45,3,65,3,4,7,7,5,4,1,45,77,95,23])
print(k)
x = np.unique(k, return_index = True)
print(x)

[ 1 22 45  3 65  3  4  7  7  5  4  1 45 77 95 23]
(array([ 1,  3,  4,  5,  7, 22, 23, 45, 65, 77, 95]), array([ 0,  3,  6,  9,  7,  1, 15,  2,  4, 13, 14]))


In [62]:
k = np.array([1,22,45,3,65,3,4,7,7,5,4,1,45,77,95,23])
print(k)
x = np.unique(k, return_index = True, return_counts = True)
print(x)

[ 1 22 45  3 65  3  4  7  7  5  4  1 45 77 95 23]
(array([ 1,  3,  4,  5,  7, 22, 23, 45, 65, 77, 95]), array([ 0,  3,  6,  9,  7,  1, 15,  2,  4, 13, 14]), array([2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1]))


In [63]:
# Delete 


In [64]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


In [69]:
x = np.array([[2,7,9,6,8], [4,5,7,1,2], [50,0,65,6,7]])
print(x)
m = np.delete(x,1,axis=0)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]


In [71]:
x = np.array([[2,7,9,6,8], [4,5,7,1,2], [50,0,65,6,7]])
print(x)
m = np.delete(x,1, axis=1)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  9  6  8]
 [ 4  7  1  2]
 [50 65  6  7]]
